# Generated by Django 5.2.9 on 2025-12-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='editor_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='parseddocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
